version: "3.9"

services:
#  db:
#    image: postgres
#    restart: always
#    command: -p 5000
#    ports:
#      - 5000:5432
#    environment:
#      POSTGRES_PASSWORD: Cib3jj7yz123
#
#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8080:8080
  web:
    build: .
    command: [ 'python', 'manage.py', 'runserver', '0.0.0.0:8000' ]
      - .:/code
    ports:
      - "8000:8000"
#    environment:
#      - POSTGRES_NAME=ano_rsi_db
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=Cib3jj7yz123
#    depends_on:
#      - db